[package]
name = "joelbrd/playerswrap"
description = "Wrapper for Roblox Players Service"
version = "1.0.22"
authors = ["Joel Broad"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Logger = "joelbrd/logger@1.0.*"
Table = "joelbrd/table@1.0.*"
CharmHub = "joelbrd/charmhub@1.0.*"
Observers = "sleitnick/observers@0.3.4"
Utils = "joelbrd/utils@1.0.*"
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.2.0"
Timer = "sleitnick/timer@1.1.2"
Concur = "sleitnick/concur@0.1.2"
Charm = "littensy/charm@0.10.0"
Future = "red-blox/future@^1.0.0"
