[package]
name = "stackyzdev/logger"
description = "Logger"
version = "1.0.0"
license = "MIT"
authors = ["Kauã Rosa Borges"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "package.json"]

[dependencies]
EnumType = "stackyzdev/enumtype@^1"
Assert = "stackyzdev/assert@^1"