[package]
name = "alemanvaldez/template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.18.3"
Promise = "evaera/promise@4.0.0"
Jecs = "ukendio/jecs@0.9.0-rc.12"
TweenService2 = "legendoj1/tweenservice2@2.2.2"
Bridgenet2 = "ffrostflame/bridgenet2@1.0.0"
Utils = "joelbrd/utils@1.0.26"
Logger = "stackyzdev/logger@1.0.0"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
SignalPlus = "coatmol/signalplus@3.3.1"
