[package]
name = "joelbrd/utils"
description = "Utils"
version = "1.0.26"
authors = ["Joel Broad"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Functions = "joelbrd/functions@1.0.*"
ConstMap = "joelbrd/constmap@1.0.*"
Table = "joelbrd/table@1.0.*"
Math = "joelbrd/math@1.0.*"
Logger = "joelbrd/logger@1.0.*"
PlayersWrap = "joelbrd/playerswrap@1.0.*"
Region = "joelbrd/region@1.0.*"
RunServiceWrap = "joelbrd/runservicewrap@1.0.*"
Promise = "evaera/promise@4.0.0"
Trove = "sleitnick/trove@1.2.0"
Future = "red-blox/future@^1.0.0"
Signal = "sleitnick/signal@2.0.1"
t = "osyrisrblx/t@3.1.1"
Concur = "sleitnick/concur@0.1.2"
