[package]
name = "joelbrd/runservicewrap"
description = "Wrapper for Roblox RunService with more full API and middlewares."
version = "1.0.5"
authors = ["Joel Broad"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Logger = "joelbrd/logger@1.0.*"
