[package]
name = "joelbrd/functions"
description = "Functions"
version = "1.0.5"
authors = ["Joel Broad"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Logger = "joelbrd/logger@1.0.*"
PlayersWrap = "joelbrd/playerswrap@1.0.*"
