[package]
name = "joelbrd/math"
description = "Math library"
version = "1.0.6"
authors = ["Joel Broad"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Logger = "joelbrd/logger@1.0.*"
Table = "joelbrd/table@1.0.*"
