[package]
name = "joelbrd/constmap"
description = "Utility function for constants stored via key/value tables"
version = "1.0.5"
authors = ["Joel Broad"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Table = "joelbrd/table@1.0.*"
Logger = "joelbrd/logger@1.0.*"
