[package]
name = "joelbrd/table"
description = "Table utilities"
version = "1.0.18"
authors = ["Joel Broad", "Sleitnick", "Pyseph#1015", "SocialSimulator"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Sift = "csqrl/sift@0.0.8"
Logger = "joelbrd/logger@1.0.*"
