[package]
name = "joelbrd/charmhub"
description = "Gives us powerful server/client syncing and debugging/peeking"
version = "1.0.4"
authors = ["Joel Broad"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Charm = "littensy/charm@0.10.0"
Signal = "sleitnick/signal@2.0.1"
Logger = "joelbrd/logger@1.0.*"
Iris = "sirmallard/iris@2.4.1"
Sift = "csqrl/sift@0.0.8"
Table = "joelbrd/table@1.0.*"
Functions = "joelbrd/functions@1.0.*"
